package reports

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Leathal1/TITO/v2/pkg/models"
	"github.com/Leathal1/TITO/v2/pkg/stridelm"
)

// MarkdownGenerator generates markdown threat intelligence reports
type MarkdownGenerator struct {
	outputDir string
}

// NewMarkdownGenerator creates a new markdown report generator
func NewMarkdownGenerator(outputDir string) *MarkdownGenerator {
	return &MarkdownGenerator{
		outputDir: outputDir,
	}
}

// Generate generates a markdown report from threats
func (m *MarkdownGenerator) Generate(threats []*models.Threat, filename string) (string, error) {
	// Create output directory if it doesn't exist
	err := os.MkdirAll(m.outputDir, 0755)
	if err != nil {
		return "", fmt.Errorf("failed to create output directory: %w", err)
	}

	// Generate filename if not provided
	if filename == "" {
		timestamp := time.Now().Format("20060102_150405")
		filename = fmt.Sprintf("threat_report_%s.md", timestamp)
	}

	reportPath := filepath.Join(m.outputDir, filename)

	// Generate content
	content := m.generateContent(threats)

	// Write to file
	err = os.WriteFile(reportPath, []byte(content), 0644)
	if err != nil {
		return "", fmt.Errorf("failed to write report: %w", err)
	}

	return reportPath, nil
}

// generateContent generates the report content
func (m *MarkdownGenerator) generateContent(threats []*models.Threat) string {
	var b strings.Builder

	// Header
	b.WriteString("# Threat Intelligence Report\n\n")
	b.WriteString(fmt.Sprintf("**Generated:** %s\n", time.Now().Format("2006-01-02 15:04 MST")))
	b.WriteString(fmt.Sprintf("**Total Threats:** %d\n\n", len(threats)))

	// Executive Summary
	b.WriteString("## Executive Summary\n\n")
	b.WriteString(m.generateSummary(threats))
	b.WriteString("\n\n")

	// Severity breakdown
	b.WriteString("## Threat Breakdown\n\n")
	b.WriteString(m.generateBreakdown(threats))
	b.WriteString("\n\n")

	// Critical threats
	critical := filterByPriority(threats, 0.7)
	if len(critical) > 0 {
		b.WriteString("## 🚨 Critical Threats - Immediate Action Required\n\n")
		b.WriteString("These threats demand immediate attention:\n\n")
		for _, threat := range critical[:min(10, len(critical))] {
			b.WriteString(m.formatThreatDetail(threat))
			b.WriteString("\n")
		}
	}

	// High priority threats
	high := filterByPriorityRange(threats, 0.5, 0.7)
	if len(high) > 0 {
		b.WriteString("## ⚠️ High Priority Threats\n\n")
		for _, threat := range high[:min(15, len(high))] {
			b.WriteString(m.formatThreatSummary(threat))
			b.WriteString("\n")
		}
	}

	// STRIDE-LM Analysis
	b.WriteString("## STRIDE-LM Analysis\n\n")
	b.WriteString(m.generateStrideAnalysis(threats))
	b.WriteString("\n\n")

	// Recommendations
	b.WriteString("## Recommended Actions\n\n")
	b.WriteString(m.generateRecommendations(threats))
	b.WriteString("\n\n")

	// Footer
	b.WriteString("---\n\n")
	b.WriteString("*Generated by TITO - Advanced Threat Intelligence Platform*\n\n")
	b.WriteString("*This report transforms chaos into actionable clarity.*\n")

	return b.String()
}

// generateSummary generates executive summary
func (m *MarkdownGenerator) generateSummary(threats []*models.Threat) string {
	if len(threats) == 0 {
		return "No threats detected in this reporting period."
	}

	var b strings.Builder

	criticalCount := len(filterByPriority(threats, 0.7))
	highCount := len(filterByPriorityRange(threats, 0.5, 0.7))

	if criticalCount > 0 {
		b.WriteString(fmt.Sprintf("**🚨 %d CRITICAL** threats require immediate action.\n\n", criticalCount))
	}

	if highCount > 0 {
		b.WriteString(fmt.Sprintf("**⚠️ %d HIGH PRIORITY** threats should be addressed soon.\n\n", highCount))
	}

	// Most common STRIDE-LM category
	catCounts := make(map[stridelm.Category]int)
	for _, threat := range threats {
		if threat.StrideProfile != nil {
			catCounts[threat.StrideProfile.PrimaryCategory]++
		}
	}

	if len(catCounts) > 0 {
		topCat, topCount := findMax(catCounts)
		catInfo := stridelm.GetCategoryInfo(topCat)
		b.WriteString(fmt.Sprintf("Primary threat vector: **%s** (%d threats)\n", catInfo.FullName, topCount))
	}

	return b.String()
}

// generateBreakdown generates severity breakdown table
func (m *MarkdownGenerator) generateBreakdown(threats []*models.Threat) string {
	severityCounts := make(map[models.ThreatSeverity]int)

	for _, threat := range threats {
		severityCounts[threat.Severity]++
	}

	var b strings.Builder
	b.WriteString("| Severity | Count |\n")
	b.WriteString("|----------|-------|\n")

	severities := []models.ThreatSeverity{
		models.SeverityCritical,
		models.SeverityHigh,
		models.SeverityMedium,
		models.SeverityLow,
		models.SeverityInfo,
	}

	icons := map[models.ThreatSeverity]string{
		models.SeverityCritical: "🔴",
		models.SeverityHigh:     "🟠",
		models.SeverityMedium:   "🟡",
		models.SeverityLow:      "🟢",
		models.SeverityInfo:     "🔵",
	}

	for _, severity := range severities {
		count := severityCounts[severity]
		icon := icons[severity]
		b.WriteString(fmt.Sprintf("| %s %s | %d |\n", icon, strings.ToUpper(string(severity)), count))
	}

	return b.String()
}

// generateStrideAnalysis generates STRIDE-LM analysis table
func (m *MarkdownGenerator) generateStrideAnalysis(threats []*models.Threat) string {
	catCounts := make(map[stridelm.Category]int)

	for _, threat := range threats {
		if threat.StrideProfile != nil {
			catCounts[threat.StrideProfile.PrimaryCategory]++
		}
	}

	if len(catCounts) == 0 {
		return "No STRIDE-LM classification data available."
	}

	var b strings.Builder
	b.WriteString("| Category | Count | Question |\n")
	b.WriteString("|----------|-------|----------|\n")

	// Sort by count (descending)
	for len(catCounts) > 0 {
		cat, count := findMax(catCounts)
		catInfo := stridelm.GetCategoryInfo(cat)
		b.WriteString(fmt.Sprintf("| %s | %d | %s |\n", catInfo.FullName, count, catInfo.Question))
		delete(catCounts, cat)
	}

	return b.String()
}

// generateRecommendations generates top recommendations
func (m *MarkdownGenerator) generateRecommendations(threats []*models.Threat) string {
	if len(threats) == 0 {
		return "No recommendations at this time."
	}

	// Collect all actions
	actionSet := make(map[string]bool)
	var actions []string

	for i, threat := range threats {
		if i >= 20 { // Top 20 threats
			break
		}
		for _, action := range threat.RecommendedActions {
			if !actionSet[action] {
				actionSet[action] = true
				actions = append(actions, action)
			}
		}
	}

	var b strings.Builder
	for i, action := range actions {
		if i >= 10 { // Top 10 actions
			break
		}
		b.WriteString(fmt.Sprintf("%d. %s\n", i+1, action))
	}

	return b.String()
}

// formatThreatDetail formats detailed threat information
func (m *MarkdownGenerator) formatThreatDetail(threat *models.Threat) string {
	var b strings.Builder

	icons := map[models.ThreatSeverity]string{
		models.SeverityCritical: "🔴",
		models.SeverityHigh:     "🟠",
		models.SeverityMedium:   "🟡",
		models.SeverityLow:      "🟢",
		models.SeverityInfo:     "🔵",
	}

	b.WriteString(fmt.Sprintf("### %s %s\n\n", icons[threat.Severity], threat.Title))
	b.WriteString(fmt.Sprintf("**Priority Score:** %.2f\n\n", threat.PriorityScore))

	if threat.StrideProfile != nil {
		catInfo := stridelm.GetCategoryInfo(threat.StrideProfile.PrimaryCategory)
		b.WriteString(fmt.Sprintf("**STRIDE-LM:** %s - *%s*\n\n", catInfo.FullName, catInfo.Question))
	}

	b.WriteString(fmt.Sprintf("**Description:** %s\n\n", threat.Description))

	if len(threat.CVEIDs) > 0 {
		b.WriteString(fmt.Sprintf("**CVEs:** %s\n\n", strings.Join(threat.CVEIDs, ", ")))
	}

	if len(threat.RecommendedActions) > 0 {
		b.WriteString("**Recommended Actions:**\n")
		for _, action := range threat.RecommendedActions[:min(3, len(threat.RecommendedActions))] {
			b.WriteString(fmt.Sprintf("- %s\n", action))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// formatThreatSummary formats summary threat information
func (m *MarkdownGenerator) formatThreatSummary(threat *models.Threat) string {
	icons := map[models.ThreatSeverity]string{
		models.SeverityCritical: "🔴",
		models.SeverityHigh:     "🟠",
		models.SeverityMedium:   "🟡",
		models.SeverityLow:      "🟢",
		models.SeverityInfo:     "🔵",
	}

	stride := ""
	if threat.StrideProfile != nil {
		stride = fmt.Sprintf(" [%s]", threat.StrideProfile.PrimaryCategory)
	}

	return fmt.Sprintf("- %s%s **%s** (Priority: %.2f)", icons[threat.Severity], stride, threat.Title, threat.PriorityScore)
}

// Helper functions

func filterByPriority(threats []*models.Threat, minPriority float64) []*models.Threat {
	filtered := make([]*models.Threat, 0)
	for _, threat := range threats {
		if threat.PriorityScore >= minPriority {
			filtered = append(filtered, threat)
		}
	}
	return filtered
}

func filterByPriorityRange(threats []*models.Threat, minPriority, maxPriority float64) []*models.Threat {
	filtered := make([]*models.Threat, 0)
	for _, threat := range threats {
		if threat.PriorityScore >= minPriority && threat.PriorityScore < maxPriority {
			filtered = append(filtered, threat)
		}
	}
	return filtered
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func findMax(m map[stridelm.Category]int) (stridelm.Category, int) {
	var maxCat stridelm.Category
	maxCount := 0
	for cat, count := range m {
		if count > maxCount {
			maxCat = cat
			maxCount = count
		}
	}
	return maxCat, maxCount
}
